🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 4/44*

[« NumPy Getting Started](003_numpy_getting_started.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Array Indexing »](005_numpy_array_indexing.ipynb)

# NumPy Creating Arrays

> 📖 **Học song song trên W3Schools:** [numpy_creating_arrays.asp](https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp)
>
> 🎯 **Trong bài này:** Create a NumPy ndarray Object · Dimensions in Arrays · 0-D Arrays · 1-D Arrays · 2-D Arrays · 3-D arrays · Check Number of Dimensions? · Higher Dimensional Arrays · ➕ Mở rộng: Các hàm tạo mảng nhanh

## Create a NumPy ndarray Object — Tạo mảng

Đối tượng mảng trong NumPy gọi là `ndarray`. Tạo bằng hàm `array()`:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


`array()` nhận list, tuple hoặc bất kỳ đối tượng giống mảng nào:

In [2]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


## Dimensions in Arrays — Số chiều

Một **chiều (dimension)** là một tầng lồng nhau của mảng. Mảng lồng nhau = mảng chứa mảng.

## 0-D Arrays — Mảng 0 chiều

Mảng 0 chiều (*scalar*) là mỗi phần tử đơn lẻ trong mảng:

In [3]:
import numpy as np

arr = np.array(42)
print(arr)

42


## 1-D Arrays — Mảng 1 chiều

Mảng chứa các phần tử 0-D gọi là mảng 1 chiều — loại mảng phổ biến nhất:

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## 2-D Arrays — Mảng 2 chiều

Mảng chứa các mảng 1-D gọi là mảng 2 chiều, thường dùng để biểu diễn **ma trận**:

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D arrays — Mảng 3 chiều

Mảng chứa các mảng 2-D:

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions? — Kiểm tra số chiều

Thuộc tính `ndim` cho biết mảng có bao nhiêu chiều:

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays — Mảng nhiều chiều hơn

Mảng có thể có bao nhiêu chiều cũng được. Dùng tham số `ndmin` để chỉ định số chiều tối thiểu:

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## ➕ Mở rộng: Các hàm tạo mảng nhanh

In [9]:
import numpy as np

print(np.zeros(5))
print(np.ones((2, 3)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.full((2, 2), 7))
print(np.eye(3))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


> 🧪 **Try it Yourself** — Tạo mảng 2 chiều biểu diễn bảng điểm 3 học sinh × 4 môn, in ra số chiều.

In [10]:
import numpy as np

scores = np.array([[8, 7, 9, 6], [5, 8, 7, 9], [9, 9, 8, 10]])
print(scores)
print("Số chiều:", scores.ndim)

[[ 8  7  9  6]
 [ 5  8  7  9]
 [ 9  9  8 10]]
Số chiều: 2


---

## 🧠 Ghi nhớ nhanh

> - Tạo mảng: `np.array(list_hoặc_tuple)` → kiểu `ndarray`.
> - 0-D scalar · 1-D vector · 2-D ma trận · 3-D…; xem số chiều: `arr.ndim`.
> - `ndmin=n` → ép số chiều tối thiểu.
> - Tạo nhanh: `zeros ones arange linspace full eye`.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `np.array([[1, 2], [3, 4]]).ndim` bằng bao nhiêu?

- **A.** 4
- **B.** 2
- **C.** 1
- **D.** 0

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: B** — 2

</details>

---

[« NumPy Getting Started](003_numpy_getting_started.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Array Indexing »](005_numpy_array_indexing.ipynb)