🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 6/44*

[« NumPy Array Indexing](005_numpy_array_indexing.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Data Types »](007_numpy_data_types.ipynb)

# NumPy Array Slicing

> 📖 **Học song song trên W3Schools:** [numpy_array_slicing.asp](https://www.w3schools.com/python/numpy/numpy_array_slicing.asp)
>
> 🎯 **Trong bài này:** Slicing arrays · Negative Slicing · STEP · Slicing 2-D Arrays

## Slicing arrays — Cắt mảng

Cắt mảng là lấy các phần tử từ chỉ số này đến chỉ số khác: `[start:end]`, hoặc có bước: `[start:end:step]`.

- Bỏ `start` → coi là `0`.
- Bỏ `end` → coi là độ dài mảng.
- Bỏ `step` → coi là `1`.

Lấy phần tử từ chỉ số 1 đến 5:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


> 📌 Kết quả **gồm** chỉ số bắt đầu, **không gồm** chỉ số kết thúc.

Từ chỉ số 4 đến hết mảng:

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


Từ đầu đến chỉ số 4 (không gồm):

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


## Negative Slicing — Cắt bằng chỉ số âm

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


## STEP — Bước nhảy

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


## Slicing 2-D Arrays — Cắt mảng 2 chiều

Từ **hàng thứ hai**, lấy các phần tử từ chỉ số 1 đến 4:

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


Từ **cả hai hàng**, lấy phần tử ở chỉ số 2:

In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


Từ cả hai hàng, lấy chỉ số 1 đến 4 — kết quả là mảng 2-D:

In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


> 🧪 **Try it Yourself** — Lấy cột điểm môn đầu tiên của tất cả học sinh (gợi ý: arr[:, 0]).

In [9]:
import numpy as np

scores = np.array([[8, 7, 9, 6], [5, 8, 7, 9], [9, 9, 8, 10]])
print(scores[:, 0])

[8 5 9]


---

## 🧠 Ghi nhớ nhanh

> - `arr[start:end:step]` — gồm `start`, **không** gồm `end`.
> - 2-D: `arr[hàng_slice, cột_slice]`; `arr[:, 0]` lấy **cả cột** 0.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `np.array([1, 2, 3, 4, 5])[::2]` cho kết quả gì?

- **A.** `[1 2]`
- **B.** `[5 3 1]`
- **C.** `[1 3 5]`
- **D.** `[2 4]`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: C** — `[1 3 5]`

</details>

---

[« NumPy Array Indexing](005_numpy_array_indexing.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Data Types »](007_numpy_data_types.ipynb)