🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 7/44*

[« NumPy Array Slicing](006_numpy_array_slicing.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Array Copy vs View »](008_numpy_copy_vs_view.ipynb)

# NumPy Data Types

> 📖 **Học song song trên W3Schools:** [numpy_data_types.asp](https://www.w3schools.com/python/numpy/numpy_data_types.asp)
>
> 🎯 **Trong bài này:** Data Types in Python · Data Types in NumPy · Checking the Data Type of an Array · Creating Arrays With a Defined Data Type · What if a Value Can Not Be Converted? · Converting Data Type on Existing Arrays

## Data Types in Python — Kiểu dữ liệu trong Python

Mặc định Python có các kiểu: `str` (chuỗi), `int` (số nguyên), `float` (số thực), `bool` (logic), `complex` (số phức).

## Data Types in NumPy — Kiểu dữ liệu trong NumPy

NumPy có thêm nhiều kiểu, ký hiệu bằng **một ký tự**:

| Ký tự | Kiểu |
|---|---|
| `i` | integer — số nguyên |
| `b` | boolean |
| `u` | unsigned integer — số nguyên không dấu |
| `f` | float — số thực |
| `c` | complex float — số phức |
| `m` | timedelta — khoảng thời gian |
| `M` | datetime — ngày giờ |
| `O` | object |
| `S` | string (bytes) |
| `U` | unicode string |
| `V` | void — khối bộ nhớ cố định |

## Checking the Data Type of an Array — Xem kiểu dữ liệu

Thuộc tính `dtype` trả về kiểu dữ liệu của mảng:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [2]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type — Chỉ định kiểu khi tạo

Dùng tham số `dtype`:

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Với `i`, `u`, `f`, `S`, `U` có thể chỉ định thêm **kích thước** (byte):

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## What if a Value Can Not Be Converted? — Không chuyển đổi được thì sao?

Nếu giá trị không thể ép sang kiểu chỉ định, NumPy báo lỗi `ValueError`:

In [5]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

## Converting Data Type on Existing Arrays — Đổi kiểu mảng có sẵn

Cách tốt nhất là tạo **bản sao** với phương thức `astype()`:

In [6]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Có thể truyền kiểu Python thay vì ký tự:

In [7]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


Chuyển số nguyên sang boolean:

In [8]:
import numpy as np

arr = np.array([1, 0, 3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


---

## 🧠 Ghi nhớ nhanh

> - Xem kiểu: `arr.dtype` · chỉ định khi tạo: `np.array(..., dtype='i4')`.
> - Ký tự: `i` int · `u` uint · `f` float · `b` bool · `S`/`U` chuỗi · `M` datetime.
> - Đổi kiểu: `arr.astype('i')` / `arr.astype(int)` → tạo **bản sao**.
> - ⚠️ Không chuyển được → `ValueError`.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Phương thức nào tạo bản sao mảng với kiểu dữ liệu khác?

- **A.** `np.cast(arr, 'i')`
- **B.** `arr.dtype('i')`
- **C.** `arr.astype('i')`
- **D.** `arr.convert('i')`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: C** — `arr.astype('i')`

</details>

---

[« NumPy Array Slicing](006_numpy_array_slicing.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Array Copy vs View »](008_numpy_copy_vs_view.ipynb)