🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 8/44*

[« NumPy Data Types](007_numpy_data_types.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Array Shape »](009_numpy_array_shape.ipynb)

# NumPy Array Copy vs View

> 📖 **Học song song trên W3Schools:** [numpy_copy_vs_view.asp](https://www.w3schools.com/python/numpy/numpy_copy_vs_view.asp)
>
> 🎯 **Trong bài này:** The Difference Between Copy and View · COPY · VIEW · Make Changes in the VIEW · Check if Array Owns its Data · ➕ Mở rộng: Slice là view!

## The Difference Between Copy and View — Copy khác View thế nào?

- **Copy** là một **mảng mới**, có dữ liệu riêng. Thay đổi bản copy **không** ảnh hưởng mảng gốc và ngược lại.
- **View** chỉ là một **cách nhìn khác** vào mảng gốc. Thay đổi view **có** ảnh hưởng mảng gốc và ngược lại.

## COPY

Tạo copy, sửa mảng gốc, rồi hiển thị cả hai:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


Bản copy **không** bị ảnh hưởng bởi thay đổi trên mảng gốc.

## VIEW

Tạo view, sửa mảng gốc:

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


View **bị** ảnh hưởng bởi thay đổi trên mảng gốc.

## Make Changes in the VIEW — Sửa trên view

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


Mảng gốc **bị** thay đổi theo view.

## Check if Array Owns its Data — Mảng có sở hữu dữ liệu không?

Thuộc tính `base` trả về `None` nếu mảng **sở hữu** dữ liệu; ngược lại trả về đối tượng gốc:

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## ➕ Mở rộng: Slice là view!

Cắt (slicing) một mảng NumPy tạo ra **view**, không phải copy — khác với list Python:

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
part = arr[1:3]
part[0] = 99
print(arr)

lst = [1, 2, 3, 4, 5]
lst_part = lst[1:3]
lst_part[0] = 99
print(lst)

[ 1 99  3  4  5]
[1, 2, 3, 4, 5]


---

## 🧠 Ghi nhớ nhanh

> - **Copy** (`arr.copy()`) → dữ liệu riêng, độc lập.
> - **View** (`arr.view()`, và cả **slice**) → dùng chung dữ liệu với mảng gốc.
> - `arr.base is None` → mảng sở hữu dữ liệu (copy); khác `None` → là view.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Sau `x = arr.view()` rồi `x[0] = 100`, mảng `arr` thế nào?

- **A.** Báo lỗi
- **B.** Không đổi
- **C.** `arr[0]` cũng thành `100`
- **D.** `arr` bị xoá

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: C** — `arr[0]` cũng thành `100`

</details>

---

[« NumPy Data Types](007_numpy_data_types.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Array Shape »](009_numpy_array_shape.ipynb)