🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 10/44*

[« NumPy Array Shape](009_numpy_array_shape.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Array Iterating »](011_numpy_array_iterating.ipynb)

# NumPy Array Reshaping

> 📖 **Học song song trên W3Schools:** [numpy_array_reshape.asp](https://www.w3schools.com/python/numpy/numpy_array_reshape.asp)
>
> 🎯 **Trong bài này:** Reshaping arrays · Reshape From 1-D to 2-D · Reshape From 1-D to 3-D · Can We Reshape Into any Shape? · Returns Copy or View? · Unknown Dimension · Flattening the arrays

## Reshaping arrays — Đổi hình dạng mảng

**Reshape** là thay đổi shape của mảng: thêm/bớt chiều, hoặc đổi số phần tử trên mỗi chiều.

## Reshape From 1-D to 2-D — Từ 1 chiều sang 2 chiều

Đổi mảng 12 phần tử thành mảng 2 chiều: 4 hàng, mỗi hàng 3 phần tử:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape From 1-D to 3-D — Từ 1 chiều sang 3 chiều

Mảng 3-D chứa 2 mảng, mỗi mảng có 3 mảng con 2 phần tử:

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Can We Reshape Into any Shape? — Reshape thành shape bất kỳ được không?

Được, **miễn là tổng số phần tử không đổi**. Mảng 8 phần tử có thể thành 2×4, nhưng **không** thể thành 3×3:

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

ValueError: cannot reshape array of size 8 into shape (3,3)

## Returns Copy or View? — Trả về copy hay view?

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


Kết quả trả về mảng gốc → `reshape` trả về **view**.

## Unknown Dimension — Chiều chưa biết

Bạn được để **một** chiều là "chưa biết" bằng cách truyền `-1` — NumPy tự tính:

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


> 📌 Không được truyền `-1` cho **nhiều hơn một** chiều.

## Flattening the arrays — Làm phẳng mảng

**Flatten** là chuyển mảng nhiều chiều thành mảng 1 chiều. Dùng `reshape(-1)`:

In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


> 💡 NumPy còn nhiều hàm đổi hình dạng khác: `flatten`, `ravel`, và để sắp xếp lại phần tử: `rot90`, `flip`, `fliplr`, `flipud`…

> 🧪 **Try it Yourself** — Biến mảng 1..24 thành mảng 2-D có 6 cột, số hàng để NumPy tự tính.

In [7]:
import numpy as np

arr = np.arange(1, 25)
print(arr.reshape(-1, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


---

## 🧠 Ghi nhớ nhanh

> - `arr.reshape(hàng, cột, ...)` — tổng số phần tử phải **không đổi**.
> - `-1` → để NumPy tự tính **một** chiều.
> - `arr.reshape(-1)` → làm phẳng thành 1-D; `reshape` trả về **view**.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Mảng 12 phần tử **không thể** reshape thành shape nào?

- **A.** `(3, 4)`
- **B.** `(12, 1)`
- **C.** `(5, 2)`
- **D.** `(2, 3, 2)`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: C** — `(5, 2)`

</details>

---

[« NumPy Array Shape](009_numpy_array_shape.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Array Iterating »](011_numpy_array_iterating.ipynb)