🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 11/44*

[« NumPy Array Reshaping](010_numpy_array_reshape.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Joining Array »](012_numpy_array_join.ipynb)

# NumPy Array Iterating

> 📖 **Học song song trên W3Schools:** [numpy_array_iterating.asp](https://www.w3schools.com/python/numpy/numpy_array_iterating.asp)
>
> 🎯 **Trong bài này:** Iterating Arrays · Iterating 2-D Arrays · Iterating 3-D Arrays · Iterating Arrays Using nditer() · Enumerated Iteration Using ndenumerate()

## Iterating Arrays — Duyệt mảng

Duyệt mảng nghĩa là đi qua từng phần tử. Với mảng nhiều chiều, ta dùng vòng `for` cơ bản của Python.

Duyệt mảng 1-D sẽ đi qua **từng phần tử**:

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


## Iterating 2-D Arrays — Duyệt mảng 2 chiều

Với mảng 2-D, vòng lặp đi qua **từng hàng**:

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


Muốn lấy từng giá trị (scalar), cần lặp lồng nhau:

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


## Iterating 3-D Arrays — Duyệt mảng 3 chiều

In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

## Iterating Arrays Using nditer() — Duyệt bằng nditer()

Hàm `nditer()` giúp duyệt **mọi phần tử** dù mảng có bao nhiêu chiều — không cần lồng nhiều vòng lặp:

In [6]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 7 8 

### Iterating Array With Different Data Types — Duyệt với kiểu dữ liệu khác

Tham số `op_dtypes` đổi kiểu dữ liệu khi duyệt. Vì NumPy không đổi kiểu tại chỗ, cần cấp thêm bộ nhớ đệm bằng `flags=['buffered']`:

In [7]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


### Iterating With Different Step Size — Duyệt với bước nhảy

Duyệt mảng 2-D, bỏ qua 1 phần tử mỗi lần:

In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


## Enumerated Iteration Using ndenumerate() — Duyệt kèm chỉ số

`ndenumerate()` trả về cả **chỉ số** lẫn **giá trị**:

In [9]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


---

## 🧠 Ghi nhớ nhanh

> - `for x in arr` → duyệt theo **chiều đầu tiên** (mảng 2-D: từng hàng).
> - `np.nditer(arr)` → duyệt **mọi phần tử** bất kể số chiều.
> - `np.ndenumerate(arr)` → duyệt kèm **chỉ số** dạng tuple.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Hàm nào duyệt qua mọi phần tử của mảng nhiều chiều mà không cần vòng lặp lồng nhau?

- **A.** `np.loop()`
- **B.** `np.iter()`
- **C.** `np.each()`
- **D.** `np.nditer()`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: D** — `np.nditer()`

</details>

---

[« NumPy Array Reshaping](010_numpy_array_reshape.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Joining Array »](012_numpy_array_join.ipynb)