🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 12/44*

[« NumPy Array Iterating](011_numpy_array_iterating.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Splitting Array »](013_numpy_array_split.ipynb)

# NumPy Joining Array

> 📖 **Học song song trên W3Schools:** [numpy_array_join.asp](https://www.w3schools.com/python/numpy/numpy_array_join.asp)
>
> 🎯 **Trong bài này:** Joining NumPy Arrays · Joining Arrays Using Stack Functions · Stacking Along Rows · Stacking Along Columns · Stacking Along Height (depth)

## Joining NumPy Arrays — Nối mảng

**Nối (join)** là đặt nội dung của hai hay nhiều mảng vào một mảng.

Trong SQL, ta nối bảng theo khoá; trong NumPy, ta nối mảng theo **trục (axis)**.

Truyền một **tuple** các mảng vào hàm `concatenate()`, kèm trục. Nếu không truyền `axis`, mặc định là `0`:

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Nối hai mảng 2-D theo **hàng** (`axis=1`):

In [2]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays Using Stack Functions — Nối bằng stack

**Stack** giống concatenate, chỉ khác là stack nối theo một **trục mới**:

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Stacking Along Rows — Xếp theo hàng

`hstack()` xếp nối tiếp theo hàng (ngang):

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Stacking Along Columns — Xếp theo cột

`vstack()` xếp chồng theo cột (dọc):

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height (depth) — Xếp theo chiều sâu

`dstack()` xếp theo chiều sâu:

In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


---

## 🧠 Ghi nhớ nhanh

> - `np.concatenate((a, b), axis=...)` — nối theo trục **có sẵn** (mặc định `axis=0`).
> - `np.stack((a, b), axis=...)` — nối theo trục **mới**.
> - `hstack` ngang · `vstack` dọc · `dstack` theo chiều sâu.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `np.vstack(([1, 2], [3, 4]))` cho kết quả có shape là gì?

- **A.** `(2, 2)`
- **B.** `(4,)`
- **C.** `(1, 4)`
- **D.** `(2, 2, 1)`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: A** — `(2, 2)`

</details>

---

[« NumPy Array Iterating](011_numpy_array_iterating.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Splitting Array »](013_numpy_array_split.ipynb)