🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 14/44*

[« NumPy Splitting Array](013_numpy_array_split.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Sorting Arrays »](015_numpy_array_sort.ipynb)

# NumPy Searching Arrays

> 📖 **Học song song trên W3Schools:** [numpy_array_search.asp](https://www.w3schools.com/python/numpy/numpy_array_search.asp)
>
> 🎯 **Trong bài này:** Searching Arrays · Search Sorted · ➕ Mở rộng: where() có 3 tham số

## Searching Arrays — Tìm kiếm trong mảng

Tìm các **chỉ số** của phần tử thoả điều kiện bằng hàm `where()`.

Tìm các chỉ số có giá trị bằng 4:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


Kết quả `(array([3, 5, 6]),)` nghĩa là giá trị 4 nằm ở chỉ số 3, 5 và 6.

Tìm chỉ số các giá trị **chẵn**:

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

print(x)

(array([1, 3, 5, 7]),)


Các giá trị **lẻ**:

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 1)

print(x)

(array([0, 2, 4, 6]),)


## Search Sorted — Tìm vị trí chèn

`searchsorted()` thực hiện **tìm kiếm nhị phân** trên mảng **đã sắp xếp**, trả về chỉ số nơi giá trị cần được chèn vào để giữ thứ tự:

In [4]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


Số 7 nên chèn ở chỉ số 1 để giữ thứ tự sắp xếp.

### Search From the Right Side — Tìm từ bên phải

Mặc định trả về chỉ số **trái nhất** phù hợp. Dùng `side='right'` để lấy chỉ số **phải nhất**:

In [5]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


### Multiple Values — Nhiều giá trị

In [6]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## ➕ Mở rộng: where() có 3 tham số

`np.where(điều_kiện, x, y)` → chọn `x` khi đúng, `y` khi sai (giống ternary cho cả mảng):

In [7]:
import numpy as np

scores = np.array([4.5, 7, 8.5, 3, 6])
print(np.where(scores >= 5, "Đậu", "Trượt"))

['Trượt' 'Đậu' 'Đậu' 'Trượt' 'Đậu']


---

## 🧠 Ghi nhớ nhanh

> - `np.where(điều_kiện)` → tuple chứa **chỉ số** thoả điều kiện.
> - `np.searchsorted(sorted_arr, v)` → vị trí chèn `v` để giữ thứ tự; `side='right'` lấy vị trí bên phải.
> - `np.where(cond, a, b)` → chọn giá trị theo điều kiện.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `np.where(np.array([5, 3, 5]) == 5)` trả về gì?

- **A.** `(array([5, 5]),)`
- **B.** `(array([0, 2]),)`
- **C.** `2`
- **D.** `[True, False, True]`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: B** — `(array([0, 2]),)`

</details>

---

[« NumPy Splitting Array](013_numpy_array_split.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Sorting Arrays »](015_numpy_array_sort.ipynb)