🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 15/44*

[« NumPy Searching Arrays](014_numpy_array_search.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Filter Array »](016_numpy_array_filter.ipynb)

# NumPy Sorting Arrays

> 📖 **Học song song trên W3Schools:** [numpy_array_sort.asp](https://www.w3schools.com/python/numpy/numpy_array_sort.asp)
>
> 🎯 **Trong bài này:** Sorting Arrays · Sorting a 2-D Array · ➕ Mở rộng: Giảm dần và argsort

## Sorting Arrays — Sắp xếp mảng

**Sắp xếp** là đặt các phần tử theo một **thứ tự**: số, chữ cái, tăng hoặc giảm dần.

Hàm `sort()` sắp xếp mảng:

In [1]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


> 📌 `np.sort()` trả về **bản sao** đã sắp xếp; mảng gốc giữ nguyên.

Sắp xếp chuỗi theo thứ tự chữ cái:

In [2]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


Sắp xếp mảng boolean:

In [3]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


## Sorting a 2-D Array — Sắp xếp mảng 2 chiều

Với mảng 2-D, **mỗi hàng** được sắp xếp riêng:

In [4]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## ➕ Mở rộng: Giảm dần và argsort

In [5]:
import numpy as np

arr = np.array([3, 1, 2])
print(np.sort(arr)[::-1])     # giảm dần
print(np.argsort(arr))        # chỉ số theo thứ tự tăng dần

names = np.array(["An", "Bình", "Chi"])
scores = np.array([7, 9, 8])
print(names[np.argsort(scores)[::-1]])   # xếp hạng theo điểm

[3 2 1]
[1 2 0]
['Bình' 'Chi' 'An']


---

## 🧠 Ghi nhớ nhanh

> - `np.sort(arr)` → **bản sao** đã sắp xếp (số, chuỗi, boolean).
> - Mảng 2-D: sắp xếp **từng hàng**.
> - Giảm dần: `np.sort(arr)[::-1]`; lấy chỉ số thứ tự: `np.argsort(arr)`.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `np.sort(np.array([[3, 1], [2, 0]]))` cho kết quả gì?

- **A.** `[[1 3] [0 2]]`
- **B.** `[[2 0] [3 1]]`
- **C.** `[0 1 2 3]`
- **D.** `[[0 1] [2 3]]`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: A** — `[[1 3] [0 2]]`

Với mảng 2-D, mỗi **hàng** được sắp xếp riêng.

</details>

---

[« NumPy Searching Arrays](014_numpy_array_search.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Filter Array »](016_numpy_array_filter.ipynb)