🔢 NumPy Tutorial › NumPy Tutorial &nbsp;·&nbsp; *Bài 16/44*

[« NumPy Sorting Arrays](015_numpy_array_sort.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Random Numbers in NumPy »](017_random_intro.ipynb)

# NumPy Filter Array

> 📖 **Học song song trên W3Schools:** [numpy_array_filter.asp](https://www.w3schools.com/python/numpy/numpy_array_filter.asp)
>
> 🎯 **Trong bài này:** Filtering Arrays · Creating the Filter Array · Creating Filter Directly From Array · ➕ Mở rộng: Kết hợp nhiều điều kiện

## Filtering Arrays — Lọc mảng

**Lọc** là lấy ra một số phần tử từ mảng có sẵn để tạo mảng mới.

Trong NumPy, ta lọc bằng **mảng boolean** (boolean index list): `True` → giữ, `False` → bỏ.

In [1]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


Ví dụ trên trả về `[41, 43]` vì chỉ số 0 và 2 là `True`.

## Creating the Filter Array — Tạo mảng lọc

Tạo mảng lọc chỉ giữ giá trị **lớn hơn 42**:

In [2]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = []

for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


Chỉ giữ số **chẵn**:

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


## Creating Filter Directly From Array — Tạo bộ lọc trực tiếp

Cách trên khá dài. NumPy cho phép **dùng thẳng điều kiện** trên mảng để tạo mảng lọc:

In [4]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## ➕ Mở rộng: Kết hợp nhiều điều kiện

Dùng `&` (và), `|` (hoặc), `~` (phủ định) — mỗi điều kiện **đặt trong ngoặc**:

In [6]:
import numpy as np

arr = np.arange(1, 21)
print(arr[(arr > 5) & (arr % 3 == 0)])
print(arr[(arr < 3) | (arr > 18)])

[ 6  9 12 15 18]
[ 1  2 19 20]


> 🧪 **Try it Yourself** — Lọc ra các điểm thi từ 8 trở lên.

In [7]:
import numpy as np

scores = np.array([6.5, 8, 9.5, 7, 8.5, 5])
print(scores[scores >= 8])

[8.  9.5 8.5]


---

## 🧠 Ghi nhớ nhanh

> - Lọc bằng mảng boolean: `arr[[True, False, ...]]`.
> - Gọn nhất: `arr[arr > 42]`, `arr[arr % 2 == 0]`.
> - Nhiều điều kiện: `arr[(cond1) & (cond2)]`, `|`, `~` — nhớ **ngoặc**.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `arr = np.array([1, 5, 8, 3])`. `arr[arr > 4]` cho kết quả gì?

- **A.** `[False True True False]`
- **B.** `[5 8]`
- **C.** `[1 3]`
- **D.** `2`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: B** — `[5 8]`

</details>

---

[« NumPy Sorting Arrays](015_numpy_array_sort.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Random Numbers in NumPy »](017_random_intro.ipynb)