🔢 NumPy Tutorial › NumPy Random &nbsp;·&nbsp; *Bài 17/44*

[« NumPy Filter Array](016_numpy_array_filter.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Random Data Distribution »](018_random_data_distribution.ipynb)

# Random Numbers in NumPy

> 📖 **Học song song trên W3Schools:** [numpy_random.asp](https://www.w3schools.com/python/numpy/numpy_random.asp)
>
> 🎯 **Trong bài này:** What is a Random Number? · Pseudo Random and True Random · Generate Random Number · Generate Random Float · Generate Random Array · Generate Random Number From Array · ➕ Mở rộng: seed

## What is a Random Number? — Số ngẫu nhiên là gì?

Số ngẫu nhiên **không** có nghĩa là mỗi lần một số khác nhau. Ngẫu nhiên nghĩa là thứ **không thể dự đoán một cách logic**.

## Pseudo Random and True Random — Giả ngẫu nhiên và ngẫu nhiên thật

Máy tính chạy theo chương trình — một tập lệnh xác định. Nên để sinh số ngẫu nhiên phải có một **thuật toán**. Nếu có thuật toán thì số đó **dự đoán được** → gọi là **giả ngẫu nhiên (pseudo random)**.

Muốn có số **ngẫu nhiên thật**, máy tính phải lấy dữ liệu từ bên ngoài: thao tác bàn phím, chuột, dữ liệu mạng…

Thông thường ta **không cần** ngẫu nhiên thật — trừ khi liên quan tới bảo mật (khoá mã hoá…). Trong bài học này, ta dùng số giả ngẫu nhiên.

## Generate Random Number — Sinh số nguyên ngẫu nhiên

NumPy có module `random` để làm việc với số ngẫu nhiên.

Sinh một số nguyên ngẫu nhiên từ 0 đến 100:

In [1]:
from numpy import random

x = random.randint(100)

print(x)

87


## Generate Random Float — Sinh số thực ngẫu nhiên

`rand()` trả về số thực ngẫu nhiên trong khoảng 0 đến 1:

In [2]:
from numpy import random

x = random.rand()

print(x)

0.012195737254510952


## Generate Random Array — Sinh mảng ngẫu nhiên

### Integers — Số nguyên

`randint()` nhận tham số `size` để chỉ định shape của mảng.

Mảng 1-D gồm 5 số nguyên ngẫu nhiên từ 0 đến 100:

In [3]:
from numpy import random

x = random.randint(100, size=(5))

print(x)

[69 85 96 94 14]


Mảng 2-D gồm 3 hàng, mỗi hàng 5 số:

In [4]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[86 90 77 12 36]
 [54  1 92 88 43]
 [66 53 52  1 21]]


### Floats — Số thực

`rand()` nhận kích thước các chiều làm đối số:

In [5]:
from numpy import random

x = random.rand(5)
print(x)

y = random.rand(3, 5)
print(y)

[0.40771418 0.58592522 0.37344605 0.89961601 0.95262623]
[[0.93076265 0.82730505 0.93285422 0.72783851 0.64351604]
 [0.69487107 0.62971733 0.25128362 0.49772584 0.20518279]
 [0.54521101 0.34625445 0.86348496 0.21921544 0.89627788]]


## Generate Random Number From Array — Chọn ngẫu nhiên từ mảng

`choice()` chọn ngẫu nhiên một giá trị từ mảng cho trước:

In [6]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

3


Thêm `size` để tạo mảng gồm các giá trị chọn từ mảng cho trước:

In [7]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 5 7 3 5]
 [9 9 7 7 9]
 [5 5 9 7 5]]


## ➕ Mở rộng: seed — kết quả có thể lặp lại

Đặt **seed** để mỗi lần chạy cho cùng một dãy số "ngẫu nhiên" (rất cần khi thí nghiệm, kiểm thử):

In [8]:
import numpy as np

np.random.seed(42)
print(np.random.randint(100, size=5))

np.random.seed(42)
print(np.random.randint(100, size=5))   # giống hệt dòng trên

rng = np.random.default_rng(seed=42)    # API hiện đại được khuyến nghị
print(rng.integers(100, size=5))

[51 92 14 71 60]
[51 92 14 71 60]
[ 8 77 65 43 43]


> 🧪 **Try it Yourself** — Mô phỏng tung xúc xắc 10 lần (giá trị từ 1 đến 6).

In [9]:
from numpy import random

print(random.randint(1, 7, size=10))

[5 2 3 3 3 5 4 3 6 5]


---

## 🧠 Ghi nhớ nhanh

> - Máy tính sinh số **giả ngẫu nhiên** (pseudo random) bằng thuật toán.
> - `random.randint(n, size=...)` số nguyên · `random.rand(...)` số thực 0–1 · `random.choice(arr, size=...)` chọn từ mảng.
> - `np.random.seed(n)` → kết quả lặp lại được.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `random.rand()` trả về giá trị trong khoảng nào?

- **A.** -1 đến 1
- **B.** 1 đến 6
- **C.** 0 đến 1
- **D.** 0 đến 100

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: C** — 0 đến 1

</details>

---

[« NumPy Filter Array](016_numpy_array_filter.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Random Data Distribution »](018_random_data_distribution.ipynb)