🔢 NumPy Tutorial › NumPy Random &nbsp;·&nbsp; *Bài 18/44*

[« Random Numbers in NumPy](017_random_intro.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Random Permutations »](019_random_permutation.ipynb)

# Random Data Distribution

> 📖 **Học song song trên W3Schools:** [numpy_random_distribution.asp](https://www.w3schools.com/python/numpy/numpy_random_distribution.asp)
>
> 🎯 **Trong bài này:** What is Data Distribution? · Random Distribution · ➕ Mở rộng: Kiểm chứng tần suất

## What is Data Distribution? — Phân phối dữ liệu là gì?

**Phân phối dữ liệu** là danh sách tất cả các giá trị có thể có, kèm **tần suất** xuất hiện của mỗi giá trị.

Đây là khái niệm rất quan trọng khi làm việc với thống kê và khoa học dữ liệu.

## Random Distribution — Phân phối ngẫu nhiên

**Phân phối ngẫu nhiên** là tập số ngẫu nhiên tuân theo một **hàm mật độ xác suất** nhất định — tức là mỗi giá trị có một **xác suất** xuất hiện riêng.

> **Hàm mật độ xác suất**: hàm mô tả xác suất liên tục, tức xác suất của mọi giá trị trong một mảng.

Dùng `choice()` với tham số `p` (xác suất cho từng giá trị). Tổng các xác suất phải bằng **1**.

Tạo mảng 1-D 100 giá trị, mỗi giá trị là 3, 5, 7 hoặc 9, với:

- Xác suất là **3**: 0.1
- Xác suất là **5**: 0.3
- Xác suất là **7**: 0.6
- Xác suất là **9**: 0

In [1]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[3 7 7 7 7 5 5 5 5 7 7 5 7 7 5 3 7 7 7 7 5 7 3 7 3 7 5 7 7 5 7 7 5 5 7 7 7
 7 7 5 7 5 7 7 7 7 7 7 7 5 5 3 7 5 5 3 5 5 7 7 5 5 5 5 5 7 5 7 5 7 7 7 7 7
 5 7 5 5 7 7 7 5 7 7 7 7 7 5 7 7 7 5 7 7 7 5 7 7 7 7]


Dù chạy bao nhiêu lần, giá trị 9 cũng **không bao giờ** xuất hiện vì xác suất của nó là 0.

Trả về mảng 2-D 3 hàng × 5 cột:

In [2]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[5 7 7 5 3]
 [7 7 7 5 7]
 [3 5 5 7 7]]


## ➕ Mở rộng: Kiểm chứng tần suất

In [3]:
import numpy as np

x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=10_000)
values, counts = np.unique(x, return_counts=True)
for v, c in zip(values, counts):
    print(v, "->", c / len(x))

3 -> 0.1001
5 -> 0.2968
7 -> 0.6031


---

## 🧠 Ghi nhớ nhanh

> - Phân phối dữ liệu = các giá trị có thể có + **tần suất** của từng giá trị.
> - `random.choice(values, p=[...], size=...)` — `p` là xác suất, **tổng phải bằng 1**.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Trong `random.choice([1, 2], p=[0.2, 0.8])`, tổng các phần tử của `p` phải bằng bao nhiêu?

- **A.** 0
- **B.** Số phần tử của mảng
- **C.** 1
- **D.** 100

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: C** — 1

</details>

---

[« Random Numbers in NumPy](017_random_intro.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Random Permutations »](019_random_permutation.ipynb)