🔢 NumPy Tutorial › NumPy Random &nbsp;·&nbsp; *Bài 19/44*

[« Random Data Distribution](018_random_data_distribution.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Seaborn »](020_random_seaborn_module.ipynb)

# Random Permutations

> 📖 **Học song song trên W3Schools:** [numpy_random_permutation.asp](https://www.w3schools.com/python/numpy/numpy_random_permutation.asp)
>
> 🎯 **Trong bài này:** Random Permutations of Elements · Shuffling Arrays · Generating Permutation of Arrays

## Random Permutations of Elements — Hoán vị ngẫu nhiên

**Hoán vị (permutation)** là một cách sắp xếp lại các phần tử. Ví dụ `[3, 2, 1]` là một hoán vị của `[1, 2, 3]`.

Module random của NumPy có hai phương thức: `shuffle()` và `permutation()`.

## Shuffling Arrays — Xáo trộn mảng

**Shuffle** đổi chỗ các phần tử **ngay trên mảng gốc**:

In [1]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 3 4 2 1]


> 📌 `shuffle()` **thay đổi mảng gốc**.

## Generating Permutation of Arrays — Tạo hoán vị

`permutation()` trả về **mảng mới** đã xáo trộn, mảng gốc giữ nguyên:

In [2]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))
print(arr)

[3 2 4 5 1]
[1 2 3 4 5]


> 🧪 **Try it Yourself** — Xáo trộn danh sách học sinh để chia nhóm ngẫu nhiên.

In [3]:
import numpy as np

students = np.array(["An", "Bình", "Chi", "Dũng", "Em", "Giang"])
shuffled = np.random.permutation(students)
print("Nhóm 1:", shuffled[:3])
print("Nhóm 2:", shuffled[3:])

Nhóm 1: ['Giang' 'Dũng' 'Chi']
Nhóm 2: ['Bình' 'An' 'Em']


---

## 🧠 Ghi nhớ nhanh

> - `random.shuffle(arr)` → xáo trộn **tại chỗ** (sửa mảng gốc).
> - `random.permutation(arr)` → trả về **mảng mới** đã xáo trộn.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Hàm nào xáo trộn mà **không** thay đổi mảng gốc?

- **A.** `random.permutation()`
- **B.** `random.choice()`
- **C.** `random.shuffle()`
- **D.** `random.sort()`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: A** — `random.permutation()`

</details>

---

[« Random Data Distribution](018_random_data_distribution.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Seaborn »](020_random_seaborn_module.ipynb)