🔢 NumPy Tutorial › NumPy Random &nbsp;·&nbsp; *Bài 26/44*

[« Logistic Distribution](025_random_logistic_distribution.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Exponential Distribution »](027_random_exponential_distribution.ipynb)

# Multinomial Distribution

> 📖 **Học song song trên W3Schools:** [numpy_random_multinomial.asp](https://www.w3schools.com/python/numpy/numpy_random_multinomial.asp)
>
> 🎯 **Trong bài này:** Multinomial Distribution

## Multinomial Distribution — Phân phối đa thức

**Phân phối đa thức** là dạng tổng quát của phân phối nhị thức.

Nó mô tả kết quả của các tình huống **nhiều khả năng** — khác với nhị thức chỉ có hai. Ví dụ: nhóm máu, kết quả tung xúc xắc.

Ba tham số:

- `n` — số lần thử.
- `pvals` — danh sách xác suất của từng kết quả (ví dụ xúc xắc: `[1/6] * 6`).
- `size` — shape của mảng trả về.

Tung xúc xắc 6 lần, đếm số lần ra mỗi mặt:

In [1]:
from numpy import random

x = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

print(x)

[1 1 0 1 3 0]


> 📌 Mẫu đa thức **không** sinh ra một giá trị đơn lẻ — nó sinh ra **một giá trị cho mỗi** phần tử của `pvals`.
>
> 📌 Vì là dạng tổng quát của nhị thức, biểu đồ và độ tương đồng với phân phối chuẩn giống như nhị thức khi có nhiều biến.

In [2]:
from numpy import random

rolls = random.multinomial(n=600, pvals=[1/6] * 6, size=3)
print(rolls)
print(rolls.sum(axis=1))   # mỗi hàng luôn có tổng = n

[[105  79  92 113  94 117]
 [100  99 107  98  91 105]
 [120 102  94  95  93  96]]
[600 600 600]


---

## 🧠 Ghi nhớ nhanh

> - Đa thức = nhị thức tổng quát, **nhiều** kết quả có thể.
> - `random.multinomial(n=..., pvals=[...], size=...)` → mỗi lần trả về **số lần đếm cho từng kết quả**.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `random.multinomial(n=6, pvals=[1/6]*6)` trả về gì?

- **A.** Mảng 6 số thực
- **B.** Mảng 6 phần tử: số lần ra từng mặt, tổng bằng 6
- **C.** Một số từ 1 đến 6
- **D.** Xác suất của mỗi mặt

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: B** — Mảng 6 phần tử: số lần ra từng mặt, tổng bằng 6

</details>

---

[« Logistic Distribution](025_random_logistic_distribution.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Exponential Distribution »](027_random_exponential_distribution.ipynb)