🔢 NumPy Tutorial › NumPy ufunc &nbsp;·&nbsp; *Bài 32/44*

[« Zipf Distribution](031_random_zipf_distribution.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Create Your Own ufunc »](033_ufunc_create_function.ipynb)

# NumPy ufuncs

> 📖 **Học song song trên W3Schools:** [numpy_ufunc.asp](https://www.w3schools.com/python/numpy/numpy_ufunc.asp)
>
> 🎯 **Trong bài này:** What are ufuncs? · Why use ufuncs? · What is Vectorization? · ➕ Mở rộng: Toán tử trên mảng cũng là ufunc

## What are ufuncs? — ufunc là gì?

**ufunc** là viết tắt của *Universal Functions* — các **hàm toàn cục** của NumPy, hoạt động trên đối tượng `ndarray`.

## Why use ufuncs? — Vì sao dùng ufunc?

ufunc thực hiện **vector hoá (vectorization)** trong NumPy — nhanh hơn nhiều so với duyệt từng phần tử.

ufunc còn hỗ trợ **broadcasting** và các phương thức bổ sung như `reduce`, `accumulate`… rất hữu ích khi tính toán.

ufunc nhận thêm các tham số:

- `where` — mảng boolean hoặc điều kiện xác định nơi phép toán được thực hiện.
- `dtype` — kiểu dữ liệu trả về.
- `out` — mảng đầu ra nơi kết quả được ghi vào.

## What is Vectorization? — Vector hoá là gì?

Chuyển các câu lệnh lặp thành **phép toán trên vector** gọi là vector hoá. CPU hiện đại được tối ưu cho các phép toán này nên chúng chạy rất nhanh.

Cộng các phần tử của hai list:

```text
list 1: [1, 2, 3, 4]
list 2: [4, 5, 6, 7]
```

Một cách là duyệt cả hai list và cộng từng cặp. Không dùng ufunc, ta dùng hàm `zip()` có sẵn của Python:

In [1]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    z.append(i + j)

print(z)

[5, 7, 9, 11]


NumPy có ufunc `add(x, y)` cho kết quả tương tự:

In [2]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


## ➕ Mở rộng: Toán tử trên mảng cũng là ufunc

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])
print(a + b)      # gọi np.add
print(a * 10)     # broadcasting: 10 được "trải" cho mọi phần tử
result = np.zeros(4, dtype=int)
np.add(a, b, out=result, where=a > 2)   # chỉ tính ở vị trí thoả điều kiện
print(result)

[ 5  7  9 11]
[10 20 30 40]
[ 0  0  9 11]


---

## 🧠 Ghi nhớ nhanh

> - ufunc = **Universal Function**, hàm NumPy chạy trên **cả mảng** (vector hoá) → rất nhanh.
> - Tham số thêm: `where`, `dtype`, `out`.
> - `np.add(x, y)` ⇔ `x + y` với mảng NumPy.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** "ufunc" là viết tắt của gì?

- **A.** Unique Function
- **B.** Universal Function
- **C.** Unified Function
- **D.** User Function

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: B** — Universal Function

</details>

---

[« Zipf Distribution](031_random_zipf_distribution.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Create Your Own ufunc »](033_ufunc_create_function.ipynb)