🔢 NumPy Tutorial › NumPy ufunc &nbsp;·&nbsp; *Bài 34/44*

[« Create Your Own ufunc](033_ufunc_create_function.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Rounding Decimals »](035_ufunc_rounding_decimals.ipynb)

# Simple Arithmetic

> 📖 **Học song song trên W3Schools:** [numpy_ufunc_simple_arithmetic.asp](https://www.w3schools.com/python/numpy/numpy_ufunc_simple_arithmetic.asp)
>
> 🎯 **Trong bài này:** Simple Arithmetic · Addition · Subtraction · Multiplication · Division · Power · Remainder · Quotient and Mod · Absolute Values

## Simple Arithmetic — Số học cơ bản

Có thể dùng trực tiếp các toán tử `+ - * /` giữa các mảng NumPy. Phần này giới thiệu các **hàm** tương ứng, nhận được mọi đối tượng giống mảng (list, tuple…) và hỗ trợ **tham số điều kiện** `where`.

## Addition — Phép cộng

In [1]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


## Subtraction — Phép trừ

In [2]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


## Multiplication — Phép nhân

In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


## Division — Phép chia

In [4]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


## Power — Luỹ thừa

In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


> ⚠️ Kết quả cuối cùng bị **tràn số** (overflow) vì 60³³ vượt quá giới hạn của kiểu `int64` — một điểm khác biệt quan trọng giữa NumPy và số nguyên Python (không giới hạn).

## Remainder — Phần dư

`mod()` và `remainder()` đều trả về phần dư:

In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

print(np.mod(arr1, arr2))
print(np.remainder(arr1, arr2))

[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]


## Quotient and Mod — Thương và dư

`divmod()` trả về **hai mảng**: thương và phần dư:

In [7]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


## Absolute Values — Giá trị tuyệt đối

`absolute()` và `abs()` cho cùng kết quả. Nên dùng `absolute()` để tránh nhầm với hàm `abs()` có sẵn của Python:

In [8]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


---

## 🧠 Ghi nhớ nhanh

> - `add subtract multiply divide power` ⇔ `+ - * / **`.
> - Phần dư: `mod`/`remainder` · thương và dư: `divmod` · trị tuyệt đối: `absolute`.
> - ⚠️ Số nguyên NumPy có giới hạn → có thể **tràn số**.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Hàm nào trả về cả **thương** và **phần dư**?

- **A.** `np.mod()`
- **B.** `np.divmod()`
- **C.** `np.remainder()`
- **D.** `np.divide()`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: B** — `np.divmod()`

</details>

---

[« Create Your Own ufunc](033_ufunc_create_function.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [Rounding Decimals »](035_ufunc_rounding_decimals.ipynb)