🔢 NumPy Tutorial › NumPy ufunc &nbsp;·&nbsp; *Bài 42/44*

[« NumPy GCD Greatest Common Denominator](041_ufunc_finding_gcd.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Hyperbolic Functions »](043_ufunc_hyperbolic.ipynb)

# NumPy Trigonometric Functions

> 📖 **Học song song trên W3Schools:** [numpy_ufunc_trigonometric.asp](https://www.w3schools.com/python/numpy/numpy_ufunc_trigonometric.asp)
>
> 🎯 **Trong bài này:** Trigonometric Functions · Convert Degrees Into Radians · Radians to Degrees · Finding Angles · Hypotenues

## Trigonometric Functions — Hàm lượng giác

NumPy có các ufunc `sin()`, `cos()`, `tan()` nhận giá trị **radian** và trả về sin, cos, tan tương ứng.

Tính sin của PI/2:

In [1]:
import numpy as np

x = np.sin(np.pi / 2)

print(x)

1.0


Tính sin cho mọi giá trị trong mảng:

In [2]:
import numpy as np

arr = np.array([np.pi / 2, np.pi / 3, np.pi / 4, np.pi / 5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


## Convert Degrees Into Radians — Đổi độ sang radian

Mặc định các hàm lượng giác nhận **radian**. Cần đổi độ sang radian:

> Radian = độ × π / 180

In [3]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


## Radians to Degrees — Đổi radian sang độ

In [4]:
import numpy as np

arr = np.array([np.pi / 2, np.pi, 1.5 * np.pi, 2 * np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


## Finding Angles — Tìm góc

Tìm góc từ giá trị sin, cos, tan (ví dụ sin, cos, tan **nghịch đảo**) bằng `arcsin()`, `arccos()`, `arctan()`:

In [5]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


### Angles of Each Value in Arrays — Góc của từng giá trị trong mảng

In [6]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


## Hypotenues — Cạnh huyền

Tính cạnh huyền theo định lý Pythagoras bằng `hypot()` (nhận hai cạnh góc vuông):

In [7]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


---

## 🧠 Ghi nhớ nhanh

> - `np.sin cos tan` nhận **radian**; nghịch đảo: `arcsin arccos arctan`.
> - Đổi đơn vị: `np.deg2rad()` / `np.rad2deg()`.
> - Cạnh huyền: `np.hypot(a, b)`.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** `np.hypot(3, 4)` bằng bao nhiêu?

- **A.** 12.0
- **B.** 5.0
- **C.** 25.0
- **D.** 7.0

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: B** — 5.0

</details>

---

[« NumPy GCD Greatest Common Denominator](041_ufunc_finding_gcd.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [NumPy Hyperbolic Functions »](043_ufunc_hyperbolic.ipynb)