🔢 NumPy Tutorial › NumPy ufunc &nbsp;·&nbsp; *Bài 44/44*

[« NumPy Hyperbolic Functions](043_ufunc_hyperbolic.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; Hoàn thành 🎉

# NumPy Set Operations

> 📖 **Học song song trên W3Schools:** [numpy_ufunc_set_operations.asp](https://www.w3schools.com/python/numpy/numpy_ufunc_set_operations.asp)
>
> 🎯 **Trong bài này:** What is a Set · Create Sets in NumPy · Finding Union · Finding Intersection · Finding Difference · Finding Symmetric Difference

## What is a Set — Tập hợp là gì?

**Tập hợp (set)** trong toán học là một nhóm các phần tử **duy nhất** (không trùng lặp).

Tập hợp dùng cho các phép toán giao, hợp, hiệu.

## Create Sets in NumPy — Tạo tập hợp

Dùng `unique()` để tìm các phần tử duy nhất của một mảng, ví dụ chuyển mảng có phần tử lặp thành tập hợp:

In [1]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


## Finding Union — Hợp

Dùng `union1d()`:

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


## Finding Intersection — Giao

Dùng `intersect1d()`:

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


> 📌 Tham số tuỳ chọn `assume_unique=True` giúp tính nhanh hơn — **chỉ** đặt khi chắc chắn các mảng đã là tập hợp (không trùng lặp).

## Finding Difference — Hiệu

Tìm các phần tử có trong tập thứ nhất mà **không** có trong tập thứ hai, dùng `setdiff1d()`:

In [4]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


## Finding Symmetric Difference — Hiệu đối xứng

Tìm các phần tử **không** có mặt ở **cả hai** tập, dùng `setxor1d()`:

In [5]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]


---

## 🧠 Ghi nhớ nhanh

> - `np.unique()` → loại trùng, tạo tập hợp (đã sắp xếp).
> - Hợp `union1d` · Giao `intersect1d` · Hiệu `setdiff1d` · Hiệu đối xứng `setxor1d`.
> - `assume_unique=True` → nhanh hơn khi chắc chắn không có phần tử trùng.

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Hàm nào tìm **giao** của hai mảng NumPy?

- **A.** `np.union1d()`
- **B.** `np.setdiff1d()`
- **C.** `np.intersect1d()`
- **D.** `np.setxor1d()`

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: C** — `np.intersect1d()`

</details>

---

[« NumPy Hyperbolic Functions](043_ufunc_hyperbolic.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; Hoàn thành 🎉