🔬 SciPy Tutorial &nbsp;·&nbsp; *Bài 7/11*

[« SciPy Sparse Data](006_scipy_sparse_data.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [SciPy Spatial Data »](008_scipy_spatial_data.ipynb)

# SciPy Graphs

> 📖 **Học song song trên W3Schools:** [scipy_graphs.php](https://www.w3schools.com/python/scipy/scipy_graphs.php)
>
> 🎯 **Trong bài này:** Working with Graphs · Adjacency Matrix · Connected Components · Dijkstra · Floyd Warshall · Bellman Ford · Depth First Order · Breadth First Order

## Working with Graphs — Làm việc với đồ thị

**Đồ thị (graph)** là cấu trúc dữ liệu cơ bản. SciPy có module `scipy.sparse.csgraph` để làm việc với đồ thị.

## Adjacency Matrix — Ma trận kề

**Ma trận kề** là ma trận `n x n`, với `n` là số đỉnh (node).

Ví dụ đồ thị vô hướng có 3 đỉnh A, B, C với các cạnh có trọng số:

```text
A — B : trọng số 1
A — C : trọng số 2
```

Ma trận kề tương ứng:

```text
     A  B  C
A:  [0  1  2]
B:  [1  0  0]
C:  [2  0  0]
```

> 📌 Với đồ thị **vô hướng**, ma trận kề **đối xứng**. Với đồ thị **có hướng**, chỉ có giá trị ở các ô thể hiện chiều của cạnh.

## Connected Components — Thành phần liên thông

Tìm các thành phần liên thông bằng `connected_components()`:

In [1]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)

print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


## Dijkstra

Dùng `dijkstra()` để tìm **đường đi ngắn nhất** từ một đỉnh tới các đỉnh khác. Tham số:

- `return_predecessors` — `True` để trả về cả đường đi.
- `indices` — chỉ số đỉnh xuất phát.
- `limit` — trọng số tối đa của đường đi.

Tìm đường ngắn nhất từ đỉnh 1 tới đỉnh 2:

In [2]:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)

print(dijkstra(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


## Floyd Warshall

`floyd_warshall()` tìm đường ngắn nhất giữa **mọi cặp** đỉnh:

In [3]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


## Bellman Ford

`bellman_ford()` cũng tìm đường ngắn nhất giữa mọi cặp đỉnh, nhưng xử lý được cả **trọng số âm**:

In [4]:
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
    [0, -1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0], dtype=int32))


## Depth First Order — Duyệt theo chiều sâu

`depth_first_order()` trả về thứ tự **duyệt theo chiều sâu (DFS)** từ một đỉnh. Tham số: đồ thị và đỉnh bắt đầu:

In [5]:
import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 0, 1],
    [1, 1, 1, 1],
    [2, 1, 1, 0],
    [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(depth_first_order(newarr, 1))

(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))


## Breadth First Order — Duyệt theo chiều rộng

`breadth_first_order()` trả về thứ tự **duyệt theo chiều rộng (BFS)**:

In [6]:
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 0, 1],
    [1, 1, 1, 1],
    [2, 1, 1, 0],
    [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(breadth_first_order(newarr, 1))

(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))


> 💡 Xem thêm về đồ thị và DFS/BFS trong chương [Python DSA — Graphs](../../07_dsa/011_dsa_graphs.ipynb).

---

## 🧠 Ghi nhớ nhanh

> - Đồ thị biểu diễn bằng **ma trận kề** `n x n` → `csr_matrix(arr)`.
> - `connected_components` thành phần liên thông · `dijkstra` đường ngắn nhất từ 1 đỉnh.
> - `floyd_warshall` mọi cặp đỉnh · `bellman_ford` hỗ trợ **trọng số âm**.
> - `depth_first_order` (DFS) · `breadth_first_order` (BFS).

---

## 📝 Exercise — Bài tập nhanh

**❓ Câu hỏi:** Thuật toán nào xử lý được đồ thị có **trọng số âm**?

- **A.** Bellman Ford
- **B.** Dijkstra
- **C.** DFS
- **D.** BFS

<details>
<summary>👉 Xem đáp án</summary>

✅ **Đáp án: A** — Bellman Ford

</details>

---

[« SciPy Sparse Data](006_scipy_sparse_data.ipynb) &nbsp;•&nbsp; [📚 Mục lục](../../README.md) &nbsp;•&nbsp; [SciPy Spatial Data »](008_scipy_spatial_data.ipynb)